GET http://localhost:5225/games 

###
GET http://localhost:5225/games/1

###
POST http://localhost:5225/games 
Content-Type: application/json

{
  
    "name": "Duna",
    "genreId": 1,
    "price": 20.00,
    "releaseDate": "2014-11-18"
}

####
PUT http://localhost:5225/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Fighter II TUrbo",
    "genreId": 2,
    "price": 9.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5225/games/1

